name: Deploy each lambda to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - "feat-pulumi-lambdas"
    paths:
      - "**/*.py"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'infra/requirements.txt'

      - name: Setup aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - id: check_bucket
        name: Get bucket
        run: |
          aws s3 ls s3://${{ secrets.S3_BUCKET }} >/dev/null 2>&1

      - name: Install deps
        run: |
          python -m pip install -r infra/requirements.txt

      - id: pulumi
        name: Pulumi up
        uses: pulumi/actions@v5
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
          BUCKET: ${{ secrets.S3_BUCKET }}
        with:
          command: up
          stack-name: dev
          work-dir: ./infra/

      - name: Pulumi outputs
        run: |
          echo "Lambdas:"
          echo "${{ steps.pulumi.outputs.lambdas }}"

